route_get_user:
    path:     /user
    defaults: { _controller: ACAApiBundle:User:get }
    requirements:
        _method: 'GET'

route_post_user:
    path:     /user
    defaults: { _controller: ACAApiBundle:User:post }
    requirements:
        _method: 'POST'

route_show_user:
    path:     /user/{slug}
    defaults: { _controller: ACAApiBundle:User:show, slug: null }
    requirements:
        _method: 'GET'

route_put_user:
    path:     /user/{slug}
    defaults: { _controller: ACAApiBundle:User:put, slug: null }
    requirements:
        _method: 'PUT'

route_delete_user:
    path:     /user/{slug}
    defaults: { _controller: ACAApiBundle:User:delete, slug: null }
    requirements:
        _method: 'DELETE'

route_get_bid:
    path:     /bid
    defaults: { _controller: ACAApiBundle:Bid:get }
    requirements:
        _method: 'GET'

route_post_bid:
    path:     /bid
    defaults: { _controller: ACAApiBundle:Bid:post }
    requirements:
        _method: 'POST'

route_show_bid:
    path:     /bid/{slug}
    defaults: { _controller: ACAApiBundle:Bid:show, slug: null }
    requirements:
        _method: 'GET'

route_put_bid:
    path:     /bid/{slug}
    defaults: { _controller: ACAApiBundle:Bid:put, slug: null }
    requirements:
        _method: 'PUT'

route_delete_bid:
    path:     /bid/{slug}
    defaults: { _controller: ACAApiBundle:bid:delete, slug: null }
    requirements:
        _method: 'DELETE'