route_index_user:
    path:     /user
    defaults: { _controller: ACAApiBundle:User:index }

route_show_user:
    path:     /user/{slug}
    defaults: { _controller: ACAApiBundle:User:show, slug: null }