services:
  db:
    class: ACAApiBundle\Services\DBCommon
    arguments: ["%database_host%", "%database_user%", "%database_password%", "%database_name%", "%database_port%"]

  rest_service:
    class: ACAApiBundle\Services\RestService
    calls:
      - [setDb, ["@db"]]

  user_provider_service:
    class: ACAApiBundle\Services\UserProvider
    calls:
      - [setDb, ["@db"]]

  login_service:
    class: ACAApiBundle\Services\LoginService
    calls:
      - [setDb, ["@db"]]
