# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        default:
            pattern: ^/
            anonymous: ~
#
#        secured_area:
#            pattern: ^/user
#            stateless: true
#            simple_preauth:
#                authenticator: apikey_authenticator
#            provider: user_provider

    encoders:
        ACAApiBundle\Model\User: sha512