# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
# Symfony ApiKeyAuthenticator
    apikey_authenticator:
        class:  ACAApiBundle\Security\ApiKeyAuthenticator
        public: false